// cSpell:words Dhivehi Krio Luxembourgish Meiteilon Nyanja Odia Sesotho Shona Sinhala Uyghur Bokmal

// These languages are supported by Gemini
const supportedPrimaryLanguageSubtags: { [key: string]: string } = {
  af: 'Afrikaans',
  sq: 'Albanian',
  am: 'Amharic',
  ar: 'Arabic',
  hy: 'Armenian',
  as: 'Assamese',
  az: 'Azerbaijani',
  eu: 'Basque',
  be: 'Belarusian',
  bn: 'Bengali',
  bs: 'Bosnian',
  bg: 'Bulgarian',
  ca: 'Catalan',
  ceb: 'Cebuano',
  zh: 'Chinese',
  co: 'Corsican',
  hr: 'Croatian',
  cs: 'Czech',
  da: 'Danish',
  dv: 'Dhivehi',
  nl: 'Dutch',
  en: 'English',
  eo: 'Esperanto',
  et: 'Estonian',
  fil: 'Filipino',
  fi: 'Finnish',
  fr: 'French',
  fy: 'Frisian',
  gl: 'Galician',
  ka: 'Georgian',
  de: 'German',
  el: 'Greek',
  gu: 'Gujarati',
  ht: 'Haitian Creole',
  ha: 'Hausa',
  haw: 'Hawaiian',
  he: 'Hebrew',
  hi: 'Hindi',
  hmn: 'Hmong',
  hu: 'Hungarian',
  is: 'Icelandic',
  ig: 'Igbo',
  id: 'Indonesian',
  ga: 'Irish',
  it: 'Italian',
  ja: 'Japanese',
  jv: 'Javanese',
  kn: 'Kannada',
  kk: 'Kazakh',
  km: 'Khmer',
  ko: 'Korean',
  kri: 'Krio',
  ku: 'Kurdish',
  ky: 'Kyrgyz',
  lo: 'Lao',
  la: 'Latin',
  lv: 'Latvian',
  lt: 'Lithuanian',
  lb: 'Luxembourgish',
  mk: 'Macedonian',
  mg: 'Malagasy',
  ms: 'Malay',
  ml: 'Malayalam',
  mt: 'Maltese',
  mi: 'Maori',
  mr: 'Marathi',
  mni: 'Meiteilon',
  mn: 'Mongolian',
  my: 'Myanmar',
  ne: 'Nepali',
  no: 'Norwegian',
  ny: 'Nyanja',
  or: 'Odia',
  ps: 'Pashto',
  fa: 'Persian',
  pl: 'Polish',
  pt: 'Portuguese',
  pa: 'Punjabi',
  ro: 'Romanian',
  ru: 'Russian',
  sm: 'Samoan',
  gd: 'Scots Gaelic',
  sr: 'Serbian',
  st: 'Sesotho',
  sn: 'Shona',
  sd: 'Sindhi',
  si: 'Sinhala',
  sk: 'Slovak',
  sl: 'Slovenian',
  so: 'Somali',
  es: 'Spanish',
  su: 'Sundanese',
  sw: 'Swahili',
  sv: 'Swedish',
  tg: 'Tajik',
  ta: 'Tamil',
  te: 'Telugu',
  th: 'Thai',
  tr: 'Turkish',
  uk: 'Ukrainian',
  ur: 'Urdu',
  ug: 'Uyghur',
  uz: 'Uzbek',
  vi: 'Vietnamese',
  cy: 'Welsh',
  xh: 'Xhosa',
  yi: 'Yiddish',
  yo: 'Yoruba',
  zu: 'Zulu',
};

const bcp47ToTranslationKeyTable: { [key: string]: string } = {
  af: 'languages.af',
  sq: 'languages.sq',
  am: 'languages.am',
  ar: 'languages.ar',
  hy: 'languages.hy',
  as: 'languages.as',
  az: 'languages.az',
  eu: 'languages.eu',
  be: 'languages.be',
  bn: 'languages.bn',
  bs: 'languages.bs',
  bg: 'languages.bg',
  ca: 'languages.ca',
  ceb: 'languages.ceb',
  zh: 'languages.zh',
  co: 'languages.co',
  hr: 'languages.hr',
  cs: 'languages.cs',
  da: 'languages.da',
  dv: 'languages.dv',
  nl: 'languages.nl',
  en: 'languages.en',
  eo: 'languages.eo',
  et: 'languages.et',
  fil: 'languages.fil',
  fi: 'languages.fi',
  fr: 'languages.fr',
  fy: 'languages.fy',
  gl: 'languages.gl',
  ka: 'languages.ka',
  de: 'languages.de',
  el: 'languages.el',
  gu: 'languages.gu',
  ht: 'languages.ht',
  ha: 'languages.ha',
  haw: 'languages.haw',
  he: 'languages.iw',
  hi: 'languages.hi',
  hmn: 'languages.hmn',
  hu: 'languages.hu',
  is: 'languages.is',
  ig: 'languages.ig',
  id: 'languages.id',
  ga: 'languages.ga',
  it: 'languages.it',
  ja: 'languages.ja',
  jv: 'languages.jv',
  kn: 'languages.kn',
  kk: 'languages.kk',
  km: 'languages.km',
  ko: 'languages.ko',
  kri: 'languages.kri',
  ku: 'languages.ku',
  ky: 'languages.ky',
  lo: 'languages.lo',
  la: 'languages.la',
  lv: 'languages.lv',
  lt: 'languages.lt',
  lb: 'languages.lb',
  mk: 'languages.mk',
  mg: 'languages.mg',
  ms: 'languages.ms',
  ml: 'languages.ml',
  mt: 'languages.mt',
  mi: 'languages.mi',
  mr: 'languages.mr',
  mni: 'languages.mni',
  mn: 'languages.mn',
  my: 'languages.my',
  ne: 'languages.ne',
  no: 'languages.no',
  ny: 'languages.ny',
  or: 'languages.or',
  ps: 'languages.ps',
  fa: 'languages.fa',
  pl: 'languages.pl',
  pt: 'languages.pt',
  pa: 'languages.pa',
  ro: 'languages.ro',
  ru: 'languages.ru',
  sm: 'languages.sm',
  gd: 'languages.gd',
  sr: 'languages.sr',
  st: 'languages.st',
  sn: 'languages.sn',
  sd: 'languages.sd',
  si: 'languages.si',
  sk: 'languages.sk',
  sl: 'languages.sl',
  so: 'languages.so',
  es: 'languages.es',
  su: 'languages.su',
  sw: 'languages.sw',
  sv: 'languages.sv',
  tg: 'languages.tg',
  ta: 'languages.ta',
  te: 'languages.te',
  th: 'languages.th',
  tr: 'languages.tr',
  uk: 'languages.uk',
  ur: 'languages.ur',
  ug: 'languages.ug',
  uz: 'languages.uz',
  vi: 'languages.vi',
  cy: 'languages.cy',
  xh: 'languages.xh',
  yi: 'languages.yi',
  yo: 'languages.yo',
  zu: 'languages.zu',
};

export function getSupportedLanguages(): readonly { code: string; name: string }[] {
  return Object.entries(supportedPrimaryLanguageSubtags).map(([code, name]) => ({ code, name }));
}

export function normalizeBcp47(bcp47: string): string {
  const key = bcp47.split('-')[0].toLowerCase();
  if (key === 'iw') {
    return 'he'; // Hebrew
  } else if (key === 'nb' || key === 'nn') {
    return 'no'; // Norwegian (Bokmal and Nynorsk are treated as Norwegian)
  }
  return key;
}

export function bcp47ToLanguageName(bcp47: string): string | undefined {
  const key = normalizeBcp47(bcp47);
  return supportedPrimaryLanguageSubtags[key];
}

export function bcp47ToTranslationKey(bcp47: string): string | undefined {
  const key = normalizeBcp47(bcp47);
  return bcp47ToTranslationKeyTable[key];
}
