# This docker-compose file is intended for local development only, specifically for Linux users.
# Release builds are handled by GitHub Actions workflows; do not use this configuration for production releases.

version: '3.8'
services:
  linux-build:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER_NAME=${USER_NAME:-dev}
        - GROUP_NAME=${GROUP_NAME:-dev}
    volumes:
      - .:/app
    environment:
      - UID=${UID}
      - GID=${GID}
    user: '${UID}:${GID}'
    command: ['sh', '-c', 'npm install && npm run build']
